### ISSUE TITLE
Error call & Error script

### ISSUE THREAD

**Issue by ImTheRhino** [tjakubo2/TTS_xwing#50] opened 2017-09-29 23:34 UTC
![20170929114903_1](https://user-images.githubusercontent.com/25953269/31039613-5bc5688e-a5c2-11e7-994e-ce83875505fe.jpg)

Seem to only happen to the visitor on a table.

**Comment by tjakubo2** [comment] 2017-09-30 12:45
This is weird, I see your opponent has old-ass dial bags next to his zone, also dials aren't named properly in the error message. If I'm right, this could be resolved by deleting those dial bags (those blue bags he has next to his zone) and letting the script pull up proper ones.

I'll fiddle with the script to make it only use proper bags. If it's possible, please ask _bryandb_ to contact me on Discord, I'll check if this list (probably spawned from chest with old bags included) was indeed the cause of it.

**Comment by tjakubo2** [comment] 2017-11-25 09:07
I wasn't contacted so assuming the old bags are indded the reason.

**Closed by tjakubo2** 2017-11-25 09:07 UTC
Labels: bug
