### ISSUE TITLE
Dials dissapear 

### ISSUE THREAD

**Issue by Hacofried** [tjakubo2/TTS_xwing#7] opened 2016-10-03 15:56 UTC
Hi all,
In many games some dials dissapear i don't know what cause the dissapearing but i seen at least 4 times in 4 different games.

**Comment by doweaver** [comment] 2016-10-05 16:03
Any chance you remember more detail here? Was this a single dial disappearing completely from the board after you clicked delete, a whole set of dials disappearing after you mapped them, etc? Just trying to narrow down what might be going on :)

**Comment by Hacofried** [comment] 2016-10-05 16:13
Sometimes only one set of dials of one ship and others 2 or more sets. Many times after reveal other ship dial of the same player.
i don't remember many other things...

**Comment by tjakubo2** [comment] 2016-10-05 19:47
I tried to play with drawing, flipping and deleting dials from few sets a bit but can't reproduce it :/

Unfortunately if I can't make this happen, I hardly can do anything. Obj.destruct() calls are already as sparse as possible and it would be reeealy surprising if one of them did this. It's an interesting problem but righ now we're shooting blind.

**Comment by Hacofried** [comment] 2016-10-05 19:58
Play some games and the problem will be appear. Atleast in half of the
games occurs.

**Comment by tjakubo2** [comment] 2016-10-05 20:28
Haven't in any of my games yet. I'm spectating a fair bit too and don't really see people reassigning dials either :(

**Comment by Hacofried** [comment] 2016-10-05 20:53
Then only occurs in spanish games?

**Comment by Belthazarus** [comment] 2017-03-06 05:25
This has happened to me and my fellow players as well.

**Comment by tjakubo2** [comment] 2017-05-25 22:05
Sadly I still don't have enough info on it, can't reproduce it. If anyone sees a pattern (like if dials were lost *generally* after yo do XXX), let me know.

**Comment by tjakubo2** [comment] 2017-07-09 23:49
Single deleted dials are now immediately restored with a notification, this should do it :)

**Closed by tjakubo2** 2017-07-09 23:49 UTC
Labels: bug, hard to reproduce
