### ISSUE TITLE
Infinite looping error when typing some dial commands incorrectly.

### ISSUE THREAD

**Issue by SkeletonPuns** [tjakubo2/TTS_xwing#26] opened 2017-05-21 18:17 UTC
Some dial commands when typed with a space before or a space after spams an error message: 

Error in Script (Global) function <update>: chunk_1:(2122,8-41): attempt to concatenate a nil value

This particular message occurs when attempting to type "r" in a ship description to see range with a space before or after it. The numbers withing the parenthesis change depending on which command is being used. Not all commands are affected by a space placed after but most seem to show the errors with a space placed before.

**Comment by tjakubo2** [comment] 2017-05-21 19:44
Hey, which version of the table you were using? Workshop one or the new update? If the new update, let me know which version it said it was on the sidebar.

**Comment by tjakubo2** [comment] 2017-05-21 19:49
Regardless, yeah, I found the cause of this issue. This will be fixed with 1.1, I'll reference and close this once the merge (and workshop update) will happen.

**Closed** 2017-05-23 07:11 UTC
Labels: bug
