### ISSUE TITLE
Cannot remove range ruler with button

### ISSUE THREAD

**Issue by smathson** [tjakubo2/TTS_xwing#6] opened 2016-09-18 05:52 UTC
A "DEL"  button appears whenever you spawn a ruler for a ship but clicking the button doesn't remove the ruler. You can right click and manually delete the ruler or trigger another "display ruler" (either with the manual "r" command on the ship or clicking the "R" button on a flipped auto dial) to remove the ruler. Interestingly enough, if multiple dials (from different ships) are visible, the "DEL" button works on all but the first one that was displayed.

PS: Just played a full multiplayer game and everything else worked flawlessly. Awesome job.

**Comment by tjakubo2** [comment] 2016-09-18 12:49
This is a very weird bug. For some reason, spawned 'DEL' button can't be clicked (doesnt get a grey shade on mouseover, doesn't trigger assigned function) and.... it's physical. Like, you can put stuff on it if it's spawned higher, obviously all other buttons in game are ghost-like, can only be clicked.

Tried few workarounds so far but nothing seems to enable this button. This smells of TTS object spawning issue since it starts working properly when you right click the ruler, click 'Custom' and then click 'Import' without changing anything. I'll fiddle with some other ways like putting this button on a ship soon.

Thanks for the report and glad you're enjoying this :)

**Comment by tjakubo2** [comment] 2016-09-28 13:53
May be fixed with: [TTS v8.1 update](http://www.berserk-games.com/forums/showthread.php?2995-Update-v8-1-Tiny-Epic-Defenders-DLC-Peek-Cards-AssetBundle-Improvements-amp-Fixes&p=13447#post13447):
> Fixed issue with script button not working on custom objects.
> Fixed script buttons causing weird physics.

I can't reproduce it for now. Another temporary fix I got to find out is having one stray ruler model out on the table - if the problem will persist, I'll just hide one of each locked and noninteractable below the table.

**Closed** 2016-09-28 13:54 UTC
